name: My First GitHub Action CI/CD
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    outputs:
      text: ${{steps.finished.outputs.text}}
    env:
      VERCEL_PROJECT_ID: $ {{secrets.VERCEL_PROJECT_ID}}
      VERCEL_ORG_ID: $ {{secrets.VERCEL_ORG_ID}}
    steps:
      - run: echo "\n Hello world"
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Version
        run: go version
      - name: Prepare for Deploy
        run: |
          mkdir build
          cd build
          touch project.json
          echo "{ \"projectId\":\"$VERCEL_PROJECT_ID\", \"orgId\":\"$VERCEL_ORG_ID\" }" > project.json
      - name: Finished setup 
        run: echo "Hurray!"
  print-hello-world2:
      needs: print-hello-world
      runs-on: ubuntu-latest
      env:
        MY_JOB_OUTPUT: ${{needs.print-hello-world.outputs.text}}
      steps:
        - run: echo "\n YOLO"
        - name: finish
          id: finished
          run: echo "::set-output name=text::fuWorld"