name: My First GitHub Action CI/CD
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "\n Hello world"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Build project
        run: node -v
      - run: tree
      - name: Finished setup 
        run: echo "Hurray!"