name: My First GitHub Action CI/CD
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: $ {{secrets.VERCEL_PROJECT_ID}}
      VERCEL_ORG_ID: $ {{secrets.VERCEL_ORG_ID}}
    steps:
      - run: echo "\n Hello world"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Build project
        run: node -v
      - name: Deploy
        run: |
          mkdir build
          cd build
          touch project.json
          echo '{"projectId":"$VERCEL_PROJECT_ID", "orgId":"$VERCEL_ORG_ID"}' > project.json
      - run: tree
      - name: Finished setup 
        run: echo "Hurray!"